# Generated by Django 2.2.7 on 2019-11-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('ts', models.DateTimeField()),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
    ]
