# Generated by Django 2.2.7 on 2019-11-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['received']},
        ),
    ]
